service: test

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    REGION: ${self:provider.region}
    SUPPLIERS_TABLE: SuppliersTable
    CATEGORIES_TABLE: CategoriesTable
    USERS_TABLE: UsersTable
    ADMINS_TABLE: AdminsTable
    PRODUCTS_TABLE: ProductsTable
    ORDERS_TABLE: OrdersTable
    LINKS_TABLE: LinksTable
    REVIEWS_TABLE: ReviewsTable
    AWS_S3_BUCKET_NAME: makiy-product-images-bucket

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Scan"
        - "dynamodb:BatchWriteItem"
        - "s3:PutObject"
        - "s3:GetObject"
        - "s3:DeleteObject"
      ## Permissions to all tables in the region
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/*"
        - "arn:aws:s3:::${self:provider.environment.AWS_S3_BUCKET_NAME}/*"

functions: ${file(./functions.yml):functions}

resources:
  Resources: ${file(./resources.yml):resources}
