service: test

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    REGION: ${self:provider.region}
    SUPPLIERS_TABLE: SuppliersTable
    CATEGORIES_TABLE: CategoriesTable
    USERS_TABLE: UsersTable
    ADMINS_TABLE: AdminsTable
    PRODUCTS_TABLE: ProductsTable
    ORDERS_TABLE: OrdersTable
    ORDER_DETAILS_TABLE: OrderDetailsTable
    REVIEWS_TABLE: ReviewsTable

  ## Set SQS and DynamoDB permissions
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Scan"
      ## Permissions to all tables in the region
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/*"

    ## Permissions to each table
    # Resource:
    #   - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.SUPPLIERS_TABLE}"
    #   - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CATEGORIES_TABLE}"
    #   - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USERS_TABLE}"
    #   - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.ADMINS_TABLE}"
    #   - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PRODUCTS_TABLE}"
    #   - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.ORDERS_TABLE}"
    #   - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.ORDER_DETAILS_TABLE}"
    #   - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.REVIEWS_TABLE}"

functions: ${file(./functions.yml):functions}

resources:
  Resources: ${file(./resources.yml):resources}
